
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class TopDesignStudio extends javax.swing.JFrame {

    
    public TopDesignStudio() {
        initComponents();
        this.setTitle("Top Design Studio");
         noweZamowienie.addActionListener(new ActionListener() {
        
            public void actionPerformed(ActionEvent e) 
            {
                
                new Zamowienie(wpisanieZamowienia).setVisible(true);
                        
            }
            
        });
          lakiernia.addActionListener(new ActionListener() {
         
            public void actionPerformed(ActionEvent e) 
            {
                
                JOptionPane.showMessageDialog(rootPane, "Sylwester Czerniewicz 697350243");
                       
                
            }
        });
        
        
       
        
                int szerokosc = Toolkit.getDefaultToolkit().getScreenSize().width;
		int wysokosc = Toolkit.getDefaultToolkit().getScreenSize().height;
		
		this.setSize(szerokosc/2, wysokosc/2);
		
		int szerokoscRamki = this.getSize().height;
		int wysokoscRamki = this.getSize().width;
		this.setLocation((szerokosc - szerokoscRamki)/2, (wysokosc - wysokoscRamki)/2);
		
		
		//this.setLocation(szerokosc/4, wysokosc/4);
		
    }
    JFrame wpisanieZamowienia = this;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        zamowienie = new javax.swing.JMenu();
        noweZamowienie = new javax.swing.JMenuItem();
        cennik = new javax.swing.JMenu();
        kontakt = new javax.swing.JMenu();
        lakiernia = new javax.swing.JMenuItem();
        stolania = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        zamowienie.setText("Zamówienie");

        noweZamowienie.setText("Nowe Zamówienie");
        zamowienie.add(noweZamowienie);

        jMenuBar1.add(zamowienie);

        cennik.setText("Cennik");
        jMenuBar1.add(cennik);

        kontakt.setText("Kontakt");

        lakiernia.setText("Lakiernia");
        kontakt.add(lakiernia);

        stolania.setText("Stolarnia");
        kontakt.add(stolania);

        jMenuBar1.add(kontakt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopDesignStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopDesignStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopDesignStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopDesignStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopDesignStudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cennik;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu kontakt;
    private javax.swing.JMenuItem lakiernia;
    private javax.swing.JMenuItem noweZamowienie;
    private javax.swing.JMenuItem stolania;
    private javax.swing.JMenu zamowienie;
    // End of variables declaration//GEN-END:variables
}
